name: MinecraftDeathSwap
version: '${project.version}'
main: me.matistan05.minecraftdeathswap.Main
api-version: 1.16
authors: [Matistan]
description: Play death swap using this plugin with your friends!
commands:
  deathswap:
    description: set up your game with this command
    usage: /<command>
permissions:
  deathswap.deathswap:
    description: Allows the player to use all /blockshuffle commands
    children:
      deathswap.add: true
      deathswap.remove: true
      deathswap.start: true
      deathswap.reset: true
      deathswap.list: true
      deathswap.help: true